### ISSUE TITLE
프로젝트 README.md 규격화

### ISSUE THREAD

**Issue by MaetDol** [Awesome-Tomato/CodeReview#14]
## Summary
현재 각 프로젝트마다 조금씩 다른 형태의 README.md 를 갖고 있습니다
추후 CI/CD를 도입해 배포 완료 후 배포링크를 README.md에 추가하고자 하는데
다른 형태로 인해 어려움을 겪고 있습니다

## AS-IS
규격화 되지 않은, 여러 형태의 README.md 파일

## TO-BE
하나의 템플릿을 구성하고, 거기서 파생되어 동일한 규격의 README.md 파일을 작성할 수 있게 할 것

**Comment by sukyoungshin** [comment]
역시 에이스! 👍 좋은 지적이네요, 의견 감사합니다!   
혹시 생각해두신 템플릿이 있으실까요? 
일단 찾아본 뒤에 다시 댓글 달아놓도록 하겠습니다.

**Comment by MaetDol** [comment]
앗.. 코멘트 사이사이에 `�` 글자가 굉장히 시선강탈이네요 🤭

따로 거창하게 완벽한 템플릿 그런건 아니구요! 
앞서 작성된 README.md 파일을 모아서 보기좋은 순서대로 정렬하고 
범용적으로 사용할 수 있게 여러 항목들을 나열하는게 목표에요

**Comment by sukyoungshin** [comment]
.. 왜 저런게 들어갔는지 모르겠네요ㅋㅋ;

아하아하 저는 전체 템플릿을 맞춰서 일관성있게 하자는 얘기신줄 알았어요! 잘못 이해했네요
readme 파일을 모으자는 취지였군요. 그러면 readme 파일 네이밍만 수정하면 되는건가요?

**Comment by MaetDol** [comment]
아 제가 말을 잘못했네요!
파일들을 모아서 비교해 템플릿을 만들자는 의미였어요!

**Comment by MaetDol** [comment]
`_template` 파일을 만들었어요

새 프로젝트를 진행할땐 해당 폴더를 복사해 작업해주시면 될 것 같아요!

수정 고생하셨습니다~
