### ISSUE TITLE
청첩장 프로젝트(WeddingCard_js) 라이브러리 및 프레임워크 의견

### ISSUE THREAD

**Issue by MaetDol** [Awesome-Tomato/CodeReview#9]
작은 기능 단위라고 보기엔 약간의 크기가 있어보여요
Next.js, React, Vuejs 등 다른 라이브러리 및 프레임워크를 허용하면 어떨까 싶어요!
@sukyoungshin

**Comment by sukyoungshin** [comment]
네 좋습니다 ! 
원하시는 라이브러리/프레임워크를 적용해주시면 될 것 같습니다! 
@MaetDol

**Comment by sukyoungshin** [comment]
건의해주신 내용 적용하였습니다. aff572039045d5100eb19036bfd6711869607fb3
추가 의견 있으시면 언제든 이슈 오픈 부탁드립니다!
